version: "3.8"

services:
    foodie:
        image: foodie
        build:
            context: ..
            dockerfile: .docker/dev.Dockerfile
        volumes: 
            - ..:/app
        ports: 
            - 8020:8080
        depends_on: 
            - "Foodie-db"
    Foodie-db:
        image: postgres:13
        environment:
            POSTGRES_PASSWORD: "12345"
            POSTGRES_USER: postgres
            POSTGRES_DB: Foodie
        ports: 
            - 15432:5432
